[package]
name = "shai-assistant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# TODO: fix versions on tui, purge unused (serde_yaml)

[dependencies]
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.22"
reqwest = {version = "0.11", features = ["json", "stream"]}

eventsource-stream = { version = "0.2.3" }
futures = { version = "0.3.28" }
futures-util = { version = "0.3.28" }
bytes = "*"

serde_json = "1.0"

tui = "*"
tui-textarea = "*"
crossterm = {version = "*", features = ["event-stream"]}
tokio = {version = "*", features = ["rt", "rt-multi-thread", "macros"]}
thiserror = {version = "*"}
